 CREATE TABLE itau.weather_data (
         id INT AUTO_INCREMENT PRIMARY KEY,
         dt INT,
         temp FLOAT,
         feels_like FLOAT,
        temp_min FLOAT,
         temp_max FLOAT,
         pressure INT,
         sea_level INT,
         grnd_level INT,
         humidity INT,
         temp_kf FLOAT,
         weather_id INT,
         weather_main VARCHAR(50),
         weather_description VARCHAR(255),
         weather_icon VARCHAR(50),
         clouds_all INT,
         wind_speed FLOAT,
         wind_deg INT,
         wind_gust FLOAT,
         visibility INT,
         pop FLOAT,
         sys_pod VARCHAR(10),
         dt_txt DATETIME
     );